# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streamschema.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streamschema.proto',
  package='streamschema',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12streamschema.proto\x12\x0cstreamschema\"\x1e\n\x06\x44\x61ta2d\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\"6\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\x12\x10\n\x08strategy\x18\x04 \x01(\t\"$\n\x05Match\x12\x0c\n\x04team\x18\x01 \x01(\t\x12\r\n\x05match\x18\x02 \x01(\t\"\xb1\x01\n\x08Position\x12\x11\n\tsensor_id\x18\x01 \x01(\x04\x12\x16\n\x0etimestamp_usec\x18\x02 \x01(\x04\x12&\n\x08location\x18\x03 \x01(\x0b\x32\x14.streamschema.Data2d\x12)\n\x0bplayer_info\x18\x04 \x01(\x0b\x32\x14.streamschema.Player\x12\'\n\nmatch_info\x18\x05 \x01(\x0b\x32\x13.streamschema.Matchb\x06proto3')
)




_DATA2D = _descriptor.Descriptor(
  name='Data2d',
  full_name='streamschema.Data2d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='streamschema.Data2d.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='streamschema.Data2d.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=66,
)


_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='streamschema.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='streamschema.Player.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='role', full_name='streamschema.Player.role', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='strategy', full_name='streamschema.Player.strategy', index=2,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=122,
)


_MATCH = _descriptor.Descriptor(
  name='Match',
  full_name='streamschema.Match',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='team', full_name='streamschema.Match.team', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match', full_name='streamschema.Match.match', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=160,
)


_POSITION = _descriptor.Descriptor(
  name='Position',
  full_name='streamschema.Position',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='streamschema.Position.sensor_id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp_usec', full_name='streamschema.Position.timestamp_usec', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='streamschema.Position.location', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player_info', full_name='streamschema.Position.player_info', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match_info', full_name='streamschema.Position.match_info', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=340,
)

_POSITION.fields_by_name['location'].message_type = _DATA2D
_POSITION.fields_by_name['player_info'].message_type = _PLAYER
_POSITION.fields_by_name['match_info'].message_type = _MATCH
DESCRIPTOR.message_types_by_name['Data2d'] = _DATA2D
DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Match'] = _MATCH
DESCRIPTOR.message_types_by_name['Position'] = _POSITION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data2d = _reflection.GeneratedProtocolMessageType('Data2d', (_message.Message,), dict(
  DESCRIPTOR = _DATA2D,
  __module__ = 'streamschema_pb2'
  # @@protoc_insertion_point(class_scope:streamschema.Data2d)
  ))
_sym_db.RegisterMessage(Data2d)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), dict(
  DESCRIPTOR = _PLAYER,
  __module__ = 'streamschema_pb2'
  # @@protoc_insertion_point(class_scope:streamschema.Player)
  ))
_sym_db.RegisterMessage(Player)

Match = _reflection.GeneratedProtocolMessageType('Match', (_message.Message,), dict(
  DESCRIPTOR = _MATCH,
  __module__ = 'streamschema_pb2'
  # @@protoc_insertion_point(class_scope:streamschema.Match)
  ))
_sym_db.RegisterMessage(Match)

Position = _reflection.GeneratedProtocolMessageType('Position', (_message.Message,), dict(
  DESCRIPTOR = _POSITION,
  __module__ = 'streamschema_pb2'
  # @@protoc_insertion_point(class_scope:streamschema.Position)
  ))
_sym_db.RegisterMessage(Position)


# @@protoc_insertion_point(module_scope)
